// web/laravel-react/resources/js/pages/Index.tsx
import React, { useEffect, useState } from 'react'
import { fetchData } from '@/utils/fetchData'
import { fetchApiData } from '@/utils/fetchApiData'
import dogImg from '@/assets/img/dog.png'
import Head from '@/components/Head'


function Index() {
    const [dog, setDog] = useState<Dog>()
    const [healthcheck, setHealthcheck] = useState()

    useEffect(() => {
        Promise.all([
            (async () => {
                const { data: dogs, error } = await fetchData(
                    'https://api.thedogapi.com/v1/images/search?limit=1'
                )
                if (error) {
                    return
                }
                setDog(dogs[0])
            })(),
            (async () => {
                const { data, error } = await fetchApiData('/api/healthcheck')
                if (error) {
                    return
                }
                setHealthcheck(data)
            })(),
        ])
    }, [])

    return (
        <>
            <Head />
            <div>
                <h1>This is the Front Page.</h1>
                <h3>Random dog of the day:</h3>
                <pre>{JSON.stringify(dog)}</pre>
                <div>
                    <img src={dogImg} alt="dog" />
                </div>
                <p>{JSON.stringify(healthcheck)}</p>
            </div>
        </>
    )
}

export default Index

// web/laravel-nuxt/frontend/pages/index.vue
<template>
  <div>
    <h1>This is the Front Page.</h1>
    <h3>Random dog of the day:</h3>
    <pre>
      {{ dog }}
    </pre>
    <div>
        <img src="~/assets/img/dog.png" alt="dog" />
    </div>
    <p>
      {{ healthcheck }}
    </p>
  </div>
</template>
<script setup>
import { useFetchApi } from "../utils/useFetchApi";

const { data: dogs } = await useFetch(
  "https://api.thedogapi.com/v1/images/search?limit=1"
);
const dog = dogs.value[0]
console.log('dog', dog)

const { data: healthcheck } = await useFetchApi("/api/healthcheck");
console.log('healthcheck', healthcheck)
</script>
